#!/usr/bin/env bash
# bootstrap-workflows.sh — generate .forgejo/workflows/release.yml for one or more
# Vidocq sub-projects, with inputs adapted to each project's io.vidocq.* deps.
#
# Usage:
#   ./bootstrap-workflows.sh <path-to-project> [<path> ...]
#
# Examples:
#   ./bootstrap-workflows.sh ../vidocq-parent       # generates minimal release.yml
#   ./bootstrap-workflows.sh ../vauban              # adds a parent_release input
#   ./bootstrap-workflows.sh ../cassini             # adds chappe/champollion/ravel/vauban/parent
#   ./bootstrap-workflows.sh ../*/                  # everything in one shot
#
# The script collects every distinct (groupId, artifactId) where the version is
# SNAPSHOT and the groupId starts with io.vidocq, across all pom.xml of the
# project (parent + dependency blocks). It then writes the release.yml with one
# `<artifact>_release` input per distinct dep.

set -euo pipefail

self_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ $# -eq 0 ]]; then
  cat >&2 <<EOF
usage: $0 <path-to-project> [<path> ...]

Generates .forgejo/workflows/release.yml for each given Vidocq sub-project,
with inputs adapted to the project's io.vidocq.* SNAPSHOT dependencies.
EOF
  exit 2
fi

# Extract distinct io.vidocq.* groupIds whose deps are SNAPSHOT (literal OR
# resolved via a ${property}). Output: one groupId per line, sorted, unique.
# We group by groupId because a "family" (e.g. all champollion-*) is released
# together → one input per upstream project, not per artifact.
collect_deps() {
  local project="$1"
  python3 - "$project" <<'PY'
import sys, re, xml.etree.ElementTree as ET
from pathlib import Path

project = Path(sys.argv[1]).resolve()
own_aids = set()       # artifactIds in this project
groupids = set()       # io.vidocq.* groupIds with at least one SNAPSHOT dep

def parse(pom):
    text = pom.read_text(encoding='utf-8', errors='replace')
    m = re.search(r'<project\b[^>]*\bxmlns="([^"]+)"', text)
    if not m: return None, None
    ns = m.group(1)
    try:
        return ET.parse(pom).getroot(), ns
    except ET.ParseError:
        return None, None

# Pass 1: collect own artifactIds.
for pom in project.rglob('pom.xml'):
    if any(part in ('target', 'node_modules') or (part != '.' and part.startswith('.')) for part in pom.parts): continue
    root, ns = parse(pom)
    if root is None: continue
    aid = root.findtext(f'{{{ns}}}artifactId')
    if aid: own_aids.add(aid)

# Pass 2: build a per-POM property map, then walk parent + dependency coords.
PROP_RE = re.compile(r'^\$\{([^}]+)\}$')
for pom in project.rglob('pom.xml'):
    if any(part in ('target', 'node_modules') or (part != '.' and part.startswith('.')) for part in pom.parts): continue
    root, ns = parse(pom)
    if root is None: continue
    props = {}
    p = root.find(f'{{{ns}}}properties')
    if p is not None:
        for child in p:
            name = child.tag.split('}', 1)[-1]
            props[name] = (child.text or '').strip()

    def resolve(v):
        m = PROP_RE.match(v or '')
        return props.get(m.group(1), '') if m else (v or '')

    def coord(elem):
        return (elem.findtext(f'{{{ns}}}groupId') or '',
                elem.findtext(f'{{{ns}}}artifactId') or '',
                elem.findtext(f'{{{ns}}}version') or '')

    for tag in (f'{{{ns}}}parent', f'{{{ns}}}dependency'):
        for elem in root.iter(tag):
            g, a, v = coord(elem)
            if not g.startswith('io.vidocq'): continue
            if a in own_aids: continue       # self-reference: release-plugin bumps it
            resolved = resolve(v)
            if resolved.endswith('-SNAPSHOT'):
                groupids.add(g)

for g in sorted(groupids):
    print(g)
PY
}

# Build a YAML-safe input key for a groupId.
# io.vidocq            → vidocq_parent_release (always the parent POM)
# io.vidocq.champollion → champollion_release
# io.vidocq.vauban      → vauban_release
input_key() {
  local groupid="$1"
  if [[ "$groupid" == "io.vidocq" ]]; then
    echo "vidocq_parent_release"
  else
    local last="${groupid##*.}"
    echo "${last}_release"
  fi
}

# Emit the release.yml content to stdout.
emit_workflow() {
  local project_name="$1"
  shift
  # bash 3.2 (macOS) + `set -u` chokes on empty arrays; build defensively.
  local deps=()
  if [[ $# -gt 0 ]]; then deps=("$@"); fi

  cat <<EOF
# Generated by Vidocq/ci/release-maven/bootstrap-workflows.sh
# Re-run that script if the project's io.vidocq.* deps change.
name: release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version (e.g. 0.1.0). Without -SNAPSHOT."
        type: string
        required: true
      next_dev_version:
        description: "Next dev version (e.g. 0.2.0-SNAPSHOT). Must end with -SNAPSHOT."
        type: string
        required: true
      dry_run:
        description: "Dry-run: build + sign + bundle without commit/tag/push/upload."
        type: choice
        required: true
        default: "false"
        options: ["false", "true"]
      auto_publish:
        description: "Promote: 'manual' (default; click Publish on Sonatype Portal) or 'auto' (publish + wait for repo1.maven.org)."
        type: choice
        required: true
        default: "manual"
        options: ["manual", "auto"]
EOF

  if (( ${#deps[@]} > 0 )); then
    for g in "${deps[@]}"; do
      local key pretty
      key=$(input_key "$g")
      # Special-case io.vidocq: only one artifact lives under that groupId
      # (vidocq-parent). For every other groupId, mention that we lock all
      # artifacts of that family at once.
      if [[ "$g" == "io.vidocq" ]]; then
        pretty="io.vidocq:vidocq-parent"
      else
        pretty="${g}:* (all artifacts under ${g})"
      fi
      cat <<EOF
      ${key}:
        description: "${pretty} — stable version (must be released on Central first)"
        type: string
        required: true
EOF
    done
  fi

  cat <<EOF

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: \${{ secrets.VIDOCQ_BOT_TOKEN }}

      - uses: https://codeberg.org/Vidocq/ci/release-maven@main
        with:
          release-version:  \${{ inputs.release_version }}
          next-dev-version: \${{ inputs.next_dev_version }}
          dry-run:          \${{ inputs.dry_run }}
          # Map 'manual'/'auto' → 'false'/'true' so the action.yml input stays boolean.
          auto-publish:     \${{ inputs.auto_publish == 'auto' && 'true' || 'false' }}
EOF

  if (( ${#deps[@]} > 0 )); then
    echo "          overrides: |"
    for g in "${deps[@]}"; do
      local key
      key=$(input_key "$g")
      # The ${{ ... }} is Forgejo Actions expression syntax, NOT bash expansion.
      # Single quotes around the format string keep it literal in the YAML output.
      # Format `groupId=version` (no artifactId) — release.sh patches every
      # io.vidocq.* dep + property under that groupId.
      printf '            %s=${{ inputs.%s }}\n' "$g" "$key"
    done
  fi

  cat <<EOF
          central-username: \${{ secrets.CENTRAL_USERNAME }}
          central-password: \${{ secrets.CENTRAL_PASSWORD }}
          gpg-private-key:  \${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase:   \${{ secrets.GPG_PASSPHRASE }}
          gpg-key-id:       \${{ secrets.GPG_KEY_ID }}
          bot-token:        \${{ secrets.VIDOCQ_BOT_TOKEN }}

      - name: Notify Slack — release success
        if: success()
        uses: https://codeberg.org/Vidocq/ci/notify-slack@main
        with:
          webhook-url:      \${{ secrets.SLACK_WEBHOOK_URL }}
          status:           release-success
          repo:             \${{ github.repository }}
          ref:              \${{ github.ref_name }}
          run-url:          \${{ github.server_url }}/\${{ github.repository }}/actions/runs/\${{ github.run_number }}
          release-version:  \${{ inputs.release_version }}
          next-dev-version: \${{ inputs.next_dev_version }}
          release-tag-url:  \${{ github.server_url }}/\${{ github.repository }}/src/tag/v\${{ inputs.release_version }}

      - name: Notify Slack — release failure
        if: failure()
        uses: https://codeberg.org/Vidocq/ci/notify-slack@main
        with:
          webhook-url:      \${{ secrets.SLACK_WEBHOOK_URL }}
          status:           release-failure
          repo:             \${{ github.repository }}
          ref:              \${{ github.ref_name }}
          run-url:          \${{ github.server_url }}/\${{ github.repository }}/actions/runs/\${{ github.run_number }}
          release-version:  \${{ inputs.release_version }}
EOF
}

process_project() {
  local project_path
  project_path=$(cd "$1" && pwd)
  local project_name
  project_name=$(basename "$project_path")

  if [[ ! -f "$project_path/pom.xml" ]]; then
    echo "⚠ skip $project_name (no pom.xml at root)" >&2
    return
  fi

  local out_dir="$project_path/.forgejo/workflows"
  local out_file="$out_dir/release.yml"
  mkdir -p "$out_dir"

  local deps=()
  while IFS= read -r line; do
    [[ -n "$line" ]] && deps+=("$line")
  done < <(collect_deps "$project_path")

  # bash 3.2 (macOS) chokes on `"${arr[@]}"` when arr is empty under `set -u`.
  if (( ${#deps[@]} > 0 )); then
    emit_workflow "$project_name" "${deps[@]}" > "$out_file"
  else
    emit_workflow "$project_name" > "$out_file"
  fi
  echo "✅ $project_name: ${#deps[@]} dep(s) → $out_file"
}

for arg in "$@"; do
  process_project "$arg"
done
